### ISSUE TITLE
Some warning from clang you probably want to see.

### ISSUE THREAD

**Issue by anirul** [AdamMagaluk/asio-ssl-mutual-auth#1]
client.cpp:127:68: warning: use of logical '||' with constant operand [-Wconstant-logical-operand]
        ctx.set_verify_mode(boost::asio::ssl::context::verify_peer || boost::asio::ssl::context::verify_fail_if_no_peer_cert);
                                                                   ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cpp:127:68: note: use '|' for a bitwise operation
        ctx.set_verify_mode(boost::asio::ssl::context::verify_peer || boost::asio::ssl::context::verify_fail_if_no_peer_cert);
                                                                   ^~
                                                                   |
1 warning generated.

Hope this help.

**Comment by AdamMagaluk** [comment]
Thanks, updated.
