### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bbbbyang** [AdamMagaluk/asio-ssl-mutual-auth#3]
initialise io_context should be updated
 ```
boost::asio::ssl::context ctx(boost::asio::ssl::context::sslv23);
```
and also for dh512.pem is small. should use dh1024.pem instead

**Comment by AdamMagaluk** [comment]
This repo hasn't been updated in 7yrs I do not plan on making changes. Feel free to create a PR or fork if needed.
